/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_MikMod_Drivers_Native_Driver
#define _Included_MikMod_Drivers_Native_Driver

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_MikMod_Drivers_Native_Driver_sysCheckAccess(JNIEnv*, jobject);
JNIEXPORT jint JNICALL Java_MikMod_Drivers_Native_Driver_sysOpenSound(JNIEnv*, jobject, jint, jint, jint, jint, jstring);
JNIEXPORT jint JNICALL Java_MikMod_Drivers_Native_Driver_sysCloseSound(JNIEnv*, jobject, jint);
JNIEXPORT jint JNICALL Java_MikMod_Drivers_Native_Driver_sysWriteBuffer(JNIEnv*, jobject, jint, jarray, jint);

#ifdef __cplusplus
}
#endif

#endif
