/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>

#ifndef _Included_MikMod_Drivers_Native_Driver_class
#define _Included_MikMod_Drivers_Native_Driver_class

#ifdef __cplusplus
extern "C" {
#endif

/* Header for class MikMod_Drivers_Native_Driver_class */

typedef struct HMikMod_Drivers_Native_Driver_class {
  Hjava_lang_Object base;
