/* DO NOT EDIT THIS FILE - it is machine generated */

#include <unistd.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <linux/soundcard.h>

#include "MikMod_Drivers_Native_0005fDriver.h"


JNIEXPORT jint JNICALL Java_MikMod_Drivers_Native_1Driver_sysCheckAccess(
                                                                        JNIEnv* theEnv,
                                                                        jobject theClass)
{
	return (access("/dev/dsp",W_OK)==0);
}

JNIEXPORT jint JNICALL Java_MikMod_Drivers_Native_1Driver_sysOpenSound(
                                                                      JNIEnv* theEnv,
                                                                      jobject theClass,
                                                                      jint iFreq,
                                                                      jint iBitsNum,
                                                                      jint iStereo,
                                                                      jint iBlockSize,
                                                                      jstring szError)
{
    int sndfd;
    if((sndfd=open("/dev/dsp",O_WRONLY))<0)
    {
        //*m_->mmIO->myerr="Cannot open sounddevice";
	return -1;
    }

    if(ioctl(sndfd, SNDCTL_DSP_SAMPLESIZE, &iBitsNum) == -1 ||
       ioctl(sndfd, SNDCTL_DSP_STEREO, &iStereo) == -1 ||
       ioctl(sndfd, SNDCTL_DSP_SPEED, &iFreq) == -1)
    {
            //*m_->mmIO->myerr = "Device can't play sound in this format";
            close(sndfd);
            return -1;
    }

    ioctl(sndfd, SNDCTL_DSP_GETBLKSIZE, &iBlockSize);

    return sndfd;
}


JNIEXPORT jint JNICALL Java_MikMod_Drivers_Native_1Driver_sysCloseSound(
                                                                       JNIEnv* theEnv,
                                                                       jobject theClass,
                                                                       jint hFile)
{
    return (close(hFile) == 0);
}

JNIEXPORT jint JNICALL Java_MikMod_Drivers_Native_1Driver_sysWriteBuffer(
                                                                        JNIEnv* theEnv,
                                                                        jobject theClass,
                                                                        jint hFile,
                                                                        jbyteArray bBuffer,
                                                                        jint iLen)
{
    return write(hFile, bBuffer, iLen);
}


