/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MikMod_Drivers_Native_0005fDriver */

#ifndef _Included_MikMod_Drivers_Native_0005fDriver
#define _Included_MikMod_Drivers_Native_0005fDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MikMod_Drivers_Native_0005fDriver
 * Method:    sysCheckAccess
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_MikMod_Drivers_Native_1Driver_sysCheckAccess
  (JNIEnv *, jobject);

/*
 * Class:     MikMod_Drivers_Native_0005fDriver
 * Method:    sysOpenSound
 * Signature: (IIIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_MikMod_Drivers_Native_1Driver_sysOpenSound
  (JNIEnv *, jobject, jint, jint, jint, jint, jstring);

/*
 * Class:     MikMod_Drivers_Native_0005fDriver
 * Method:    sysCloseSound
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MikMod_Drivers_Native_1Driver_sysCloseSound
  (JNIEnv *, jobject, jint);

/*
 * Class:     MikMod_Drivers_Native_0005fDriver
 * Method:    sysWriteBuffer
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_MikMod_Drivers_Native_1Driver_sysWriteBuffer
  (JNIEnv *, jobject, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
