/* DO NOT EDIT THIS FILE - it is machine generated */

#include <unistd.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <linux/soundcard.h>
#include <stdio.h>
#include <stdlib.h>

/*
 Invocation : play_raw Freq m/s 8/16
 */
int main(int argc, char * argv[])
{

    int sndfd;
    if((sndfd=open("/dev/dsp",O_WRONLY))<0)
    {
        //*m_->mmIO->myerr="Cannot open sounddevice";
	return -1;
    }

    int iBitsNum, iStereo, iFreq, iBlockSize;
    iBlockSize = 4096;

    sscanf(argv[1], "%i", &iFreq);
    if (argv[2][0] == 's')
        iStereo = 1;
    else
        iStereo = 0;
    sscanf(argv[3], "%i", &iBitsNum);

    if(ioctl(sndfd, SNDCTL_DSP_SAMPLESIZE, &iBitsNum) == -1 ||
       ioctl(sndfd, SNDCTL_DSP_STEREO, &iStereo) == -1 ||
       ioctl(sndfd, SNDCTL_DSP_SPEED, &iFreq) == -1)
    {
            //*m_->mmIO->myerr = "Device can't play sound in this format";
            close(sndfd);
            return -1;
    }

    ioctl(sndfd, SNDCTL_DSP_GETBLKSIZE, &iBlockSize);

    FILE * input = fopen("music.raw", "r");

    int buffer_len;
    char * buffer = (char *)malloc(iBlockSize);
    buffer_len = fread(buffer, 1, iBlockSize, input);
    while (buffer_len == iBlockSize)
    {
        write(sndfd, buffer, iBlockSize);
        buffer_len = fread(buffer, 1, iBlockSize, input);
    }

    fclose(input);
    close(sndfd);
    free(buffer);

    return 0;
}


